"""Create new royalties table

Revision ID: 2a3e07749256
Revises: abf630c5d2a8
Create Date: 2024-05-01 09:46:48.606081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3e07749256'
down_revision: Union[str, None] = 'abf630c5d2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('royalties', sa.Column('created_by_email', sa.String(), nullable=False))
    op.drop_column('royalties', 'deposited_by_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('royalties', sa.Column('deposited_by_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('royalties', 'created_by_email')
    # ### end Alembic commands ###
