"""parition -> partition

Revision ID: 61d8113dc32e
Revises: 917ca33aa0b9
Create Date: 2024-05-01 09:51:05.840248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d8113dc32e'
down_revision: Union[str, None] = '917ca33aa0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('royalty_claims', sa.Column('partition_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'royalty_claims', ['id'])
    op.drop_constraint('royalty_claims_parition_id_fkey', 'royalty_claims', type_='foreignkey')
    op.create_foreign_key(None, 'royalty_claims', 'partitions', ['partition_id'], ['id'])
    op.drop_column('royalty_claims', 'parition_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('royalty_claims', sa.Column('parition_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'royalty_claims', type_='foreignkey')
    op.create_foreign_key('royalty_claims_parition_id_fkey', 'royalty_claims', 'partitions', ['parition_id'], ['id'])
    op.drop_constraint(None, 'royalty_claims', type_='unique')
    op.drop_column('royalty_claims', 'partition_id')
    # ### end Alembic commands ###
