"""create withdrawal method table

Revision ID: 7fb4910067f3
Revises: 61d8113dc32e
Create Date: 2024-05-01 20:13:36.403358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb4910067f3'
down_revision: Union[str, None] = '61d8113dc32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'withdrawal_methods', ['id'])
    op.add_column('withdrawals', sa.Column('withdrawal_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'withdrawals', 'withdrawal_methods', ['withdrawal_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.drop_column('withdrawals', 'withdrawal_method_id')
    op.drop_constraint(None, 'withdrawal_methods', type_='unique')
    # ### end Alembic commands ###
