"""fix blockchain column naming

Revision ID: 889841375bca
Revises: 996a10354503
Create Date: 2024-05-05 10:24:12.565432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889841375bca'
down_revision: Union[str, None] = '996a10354503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('blockchain_network_id', sa.Integer(), nullable=False))
    op.add_column('withdrawals', sa.Column('blockchain_currency_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'withdrawals', 'blockchain_currencies', ['blockchain_currency_id'], ['id'])
    op.create_foreign_key(None, 'withdrawals', 'blockchain_networks', ['blockchain_network_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.drop_column('withdrawals', 'blockchain_currency_id')
    op.drop_column('withdrawals', 'blockchain_network_id')
    # ### end Alembic commands ###
