"""Create royalty_claims table

Revision ID: 917ca33aa0b9
Revises: 2a3e07749256
Create Date: 2024-05-01 09:49:04.165898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917ca33aa0b9'
down_revision: Union[str, None] = '2a3e07749256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('royalty_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('royalty_id', sa.UUID(), nullable=False),
    sa.Column('parition_id', sa.UUID(), nullable=False),
    sa.Column('amount_to_claim', sa.Float(), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parition_id'], ['partitions.id'], ),
    sa.ForeignKeyConstraint(['royalty_id'], ['royalties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('royalty_claims')
    # ### end Alembic commands ###
