"""create blockchain_address on withdrawals table

Revision ID: 9794a44f0693
Revises: 28c2da5f36b7
Create Date: 2024-05-05 09:56:22.469264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9794a44f0693'
down_revision: Union[str, None] = '28c2da5f36b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('blockchain_address', sa.String(), nullable=True))
    op.alter_column('withdrawals', 'wallet_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('withdrawals', 'withdrawal_status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('withdrawals', 'withdrawal_method_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdrawals', 'withdrawal_method_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('withdrawals', 'withdrawal_status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('withdrawals', 'wallet_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('withdrawals', 'blockchain_address')
    # ### end Alembic commands ###
