"""create blockchain_currency and blockchain_network tables

Revision ID: aaa0490de8be
Revises: 9794a44f0693
Create Date: 2024-05-05 10:10:56.289847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa0490de8be'
down_revision: Union[str, None] = '9794a44f0693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blockchain_currencies', ['id'])
    op.create_unique_constraint(None, 'blockchain_networks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blockchain_networks', type_='unique')
    op.drop_constraint(None, 'blockchain_currencies', type_='unique')
    # ### end Alembic commands ###
