"""Add remove 'naeku_id' column from digital_assets table

Revision ID: abf630c5d2a8
Revises: bdbbce32f481
Create Date: 2024-04-14 09:46:21.757198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf630c5d2a8'
down_revision: Union[str, None] = 'bdbbce32f481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digital_assets', 'naeku_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_assets', sa.Column('naeku_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
