"""Add 'artist_name' column to digital_assets table

Revision ID: bdbbce32f481
Revises: 479b7d7b2886
Create Date: 2024-04-14 09:14:24.555088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbbce32f481'
down_revision: Union[str, None] = '479b7d7b2886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_assets', sa.Column('naeku_id', sa.UUID(), nullable=False))
    op.add_column('digital_assets', sa.Column('artist_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'digital_assets', ['id'])
    op.create_unique_constraint(None, 'partition_events', ['id'])
    op.create_unique_constraint(None, 'partition_statuses', ['id'])
    op.create_unique_constraint(None, 'partitions', ['id'])
    op.create_unique_constraint(None, 'royalties', ['id'])
    op.create_unique_constraint(None, 'wallets', ['id'])
    op.create_unique_constraint(None, 'withdrawal_statuses', ['id'])
    op.create_unique_constraint(None, 'withdrawals', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawals', type_='unique')
    op.drop_constraint(None, 'withdrawal_statuses', type_='unique')
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_constraint(None, 'royalties', type_='unique')
    op.drop_constraint(None, 'partitions', type_='unique')
    op.drop_constraint(None, 'partition_statuses', type_='unique')
    op.drop_constraint(None, 'partition_events', type_='unique')
    op.drop_constraint(None, 'digital_assets', type_='unique')
    op.drop_column('digital_assets', 'artist_name')
    op.drop_column('digital_assets', 'naeku_id')
    # ### end Alembic commands ###
